import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Hero from "./components/layout/Hero";
import { Providers } from "./providers";
import Navbar from "./components/layout/Navbar";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body className={inter.className}>
        <Navbar/>
        
         {/* hero */}
         
         <Providers>
          <ThemeProvider>
            <Hero/>
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}
